# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cep2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_door_win(object):
    def setupUi(self, door_win):
        door_win.setObjectName("door_win")
        door_win.resize(655, 385)
        door_win.setMinimumSize(QtCore.QSize(655, 385))
        door_win.setMaximumSize(QtCore.QSize(655, 385))
        door_win.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(41, 48, 54, 255), stop:1 rgba(101, 91, 76, 255));")
        self.centralwidget = QtWidgets.QWidget(door_win)
        self.centralwidget.setObjectName("centralwidget")
        self.nextpushButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextpushButton.setGeometry(QtCore.QRect(520, 340, 91, 23))
        self.nextpushButton.setStyleSheet("background:none;\n"
"font:  \"Tahoma\";\n"
"color:black;")
        self.nextpushButton.setObjectName("nextpushButton")
        self.doortypetext = QtWidgets.QLabel(self.centralwidget)
        self.doortypetext.setGeometry(QtCore.QRect(50, 130, 131, 31))
        self.doortypetext.setStyleSheet("background:none;\n"
"font: 10pt \"Tahoma\";\n"
"color:white;")
        self.doortypetext.setObjectName("doortypetext")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(220, 30, 241, 71))
        self.title.setStyleSheet("font: 28pt \"Helvetica\";\n"
"background:none;\n"
"color:white;")
        self.title.setObjectName("title")
        self.doordropdown = QtWidgets.QComboBox(self.centralwidget)
        self.doordropdown.setGeometry(QtCore.QRect(50, 170, 131, 22))
        self.doordropdown.setStyleSheet("background:none;\n"
"font:  \"Tahoma\";\n"
"color:black;")
        self.doordropdown.setObjectName("doordropdown")
        self.doordropdown.addItem("")
        self.doordropdown.addItem("")
        self.door_text = QtWidgets.QLabel(self.centralwidget)
        self.door_text.setGeometry(QtCore.QRect(220, 140, 91, 20))
        self.door_text.setStyleSheet("background:none;\n"
"font: 10pt \"Tahoma\";\n"
"color:white;")
        self.door_text.setObjectName("door_text")
        self.ortationdrop_1 = QtWidgets.QComboBox(self.centralwidget)
        self.ortationdrop_1.setGeometry(QtCore.QRect(380, 170, 71, 22))
        self.ortationdrop_1.setStyleSheet("background:none;\n"
"font:  \"Tahoma\";\n"
"color:black;")
        self.ortationdrop_1.setObjectName("ortationdrop_1")
        self.ortationdrop_1.addItem("")
        self.ortationdrop_1.addItem("")
        self.ortationdrop_1.addItem("")
        self.ortationdrop_1.addItem("")
        self.textortation = QtWidgets.QLabel(self.centralwidget)
        self.textortation.setGeometry(QtCore.QRect(360, 140, 111, 20))
        self.textortation.setStyleSheet("background:none;\n"
"font: 10pt \"Tahoma\";\n"
"color:white;")
        self.textortation.setObjectName("textortation")
        self.backbutton = QtWidgets.QPushButton(self.centralwidget)
        self.backbutton.setGeometry(QtCore.QRect(20, 30, 91, 23))
        self.backbutton.setStyleSheet("background:none;\n"
"font:  \"Tahoma\";\n"
"color:black;")
        self.backbutton.setObjectName("backbutton")
        self.doordropdown_2 = QtWidgets.QComboBox(self.centralwidget)
        self.doordropdown_2.setGeometry(QtCore.QRect(220, 170, 131, 22))
        self.doordropdown_2.setStyleSheet("background:none;\n"
"font:  \"Tahoma\";\n"
"color:black;")
        self.doordropdown_2.setObjectName("doordropdown_2")
        self.doordropdown_2.addItem("")
        self.doordropdown_2.addItem("")
        self.doordropdown_2.addItem("")
        self.doordropdown_2.addItem("")
        self.lng_temp_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lng_temp_1.setGeometry(QtCore.QRect(220, 220, 91, 20))
        self.lng_temp_1.setStyleSheet("background:none;\n"
"font:  \"Tahoma\";\n"
"color:black;")
        self.lng_temp_1.setObjectName("lng_temp_1")
        self.widthtext = QtWidgets.QLabel(self.centralwidget)
        self.widthtext.setGeometry(QtCore.QRect(100, 260, 81, 20))
        self.widthtext.setStyleSheet("background:none;\n"
"font: 10pt \"Tahoma\";\n"
"color:white;")
        self.widthtext.setObjectName("widthtext")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 310, 161, 16))
        self.label.setStyleSheet("background:none;\n"
"font: 8pt \"Tahoma\";\n"
"color:white;")
        self.label.setObjectName("label")
        self.wd_temp_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.wd_temp_1.setGeometry(QtCore.QRect(220, 260, 91, 20))
        self.wd_temp_1.setStyleSheet("background:none;\n"
"font:  \"Tahoma\";\n"
"color:black;")
        self.wd_temp_1.setObjectName("wd_temp_1")
        self.lenghttext = QtWidgets.QLabel(self.centralwidget)
        self.lenghttext.setGeometry(QtCore.QRect(100, 220, 111, 20))
        self.lenghttext.setStyleSheet("background:none;\n"
"font: 10pt \"Tahoma\";\n"
"color:white;")
        self.lenghttext.setObjectName("lenghttext")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 350, 161, 16))
        self.label_2.setStyleSheet("background:none;\n"
"font: 8pt \"Tahoma\";\n"
"color:white;")
        self.label_2.setObjectName("label_2")
        self.rl = QtWidgets.QLabel(self.centralwidget)
        self.rl.setGeometry(QtCore.QRect(290, 310, 55, 16))
        self.rl.setStyleSheet("background:none;\n"
"font: 8pt \"Tahoma\";\n"
"color:white;")
        self.rl.setObjectName("rl")
        self.cl = QtWidgets.QLabel(self.centralwidget)
        self.cl.setGeometry(QtCore.QRect(290, 350, 55, 16))
        self.cl.setStyleSheet("background:none;\n"
"font: 8pt \"Tahoma\";\n"
"color:white;")
        self.cl.setObjectName("cl")
        self.floor = QtWidgets.QComboBox(self.centralwidget)
        self.floor.setGeometry(QtCore.QRect(510, 170, 81, 22))
        self.floor.setStyleSheet("background:none;\n"
"font:  \"Tahoma\";\n"
"color:black;")
        self.floor.setObjectName("floor")
        self.floor.addItem("")
        self.floor.addItem("")
        self.textortation_2 = QtWidgets.QLabel(self.centralwidget)
        self.textortation_2.setGeometry(QtCore.QRect(510, 140, 51, 20))
        self.textortation_2.setStyleSheet("background:none;\n"
"font: 10pt \"Tahoma\";\n"
"color:white;")
        self.textortation_2.setObjectName("textortation_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(430, 250, 111, 31))
        self.label_3.setStyleSheet("background:none;\n"
"font: 8pt \"Tahoma\";\n"
"color:white;")
        self.label_3.setObjectName("label_3")
        door_win.setCentralWidget(self.centralwidget)

        self.retranslateUi(door_win)
        QtCore.QMetaObject.connectSlotsByName(door_win)

    def retranslateUi(self, door_win):
        _translate = QtCore.QCoreApplication.translate
        door_win.setWindowTitle(_translate("door_win", "MainWindow"))
        self.nextpushButton.setText(_translate("door_win", "NEXT"))
        self.doortypetext.setText(_translate("door_win", "Door Type"))
        self.title.setText(_translate("door_win", "HVAC CEP"))
        self.doordropdown.setItemText(0, _translate("door_win", "Single Pane"))
        self.doordropdown.setItemText(1, _translate("door_win", "Double Pane"))
        self.door_text.setText(_translate("door_win", "Door"))
        self.ortationdrop_1.setItemText(0, _translate("door_win", "North"))
        self.ortationdrop_1.setItemText(1, _translate("door_win", "South"))
        self.ortationdrop_1.setItemText(2, _translate("door_win", "East"))
        self.ortationdrop_1.setItemText(3, _translate("door_win", "West"))
        self.textortation.setText(_translate("door_win", "Oritation"))
        self.backbutton.setText(_translate("door_win", "BACK"))
        self.doordropdown_2.setItemText(0, _translate("door_win", "1"))
        self.doordropdown_2.setItemText(1, _translate("door_win", "2"))
        self.doordropdown_2.setItemText(2, _translate("door_win", "3"))
        self.doordropdown_2.setItemText(3, _translate("door_win", "4"))
        self.widthtext.setText(_translate("door_win", "Width (ft)"))
        self.label.setText(_translate("door_win", "The total Radiation load is "))
        self.lenghttext.setText(_translate("door_win", "Length(ft)"))
        self.label_2.setText(_translate("door_win", "The total Conduction load is "))
        self.rl.setText(_translate("door_win", ""))
        self.cl.setText(_translate("door_win", ""))
        self.floor.setItemText(0, _translate("door_win", "Ground"))
        self.floor.setItemText(1, _translate("door_win", "First"))
        self.textortation_2.setText(_translate("door_win", "Floor"))
        self.label_3.setText(_translate("door_win", ""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    door_win = QtWidgets.QMainWindow()
    ui = Ui_door_win()
    ui.setupUi(door_win)
    door_win.show()
    sys.exit(app.exec_())
