# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cep4.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_select_win(object):
    def setupUi(self, select_win):
        select_win.setObjectName("select_win")
        select_win.resize(529, 369)
        select_win.setMinimumSize(QtCore.QSize(529, 369))
        select_win.setMaximumSize(QtCore.QSize(529, 369))
        select_win.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(41, 48, 54, 255), stop:1 rgba(101, 91, 76, 255));")
        self.centralwidget = QtWidgets.QWidget(select_win)
        self.centralwidget.setObjectName("centralwidget")
        self.next = QtWidgets.QPushButton(self.centralwidget)
        self.next.setGeometry(QtCore.QRect(230, 230, 75, 23))
        self.next.setStyleSheet("background:none;\n"
"font:  \"Tahoma\";\n"
"color:black;")
        self.next.setObjectName("next")
        self.textcity = QtWidgets.QLabel(self.centralwidget)
        self.textcity.setGeometry(QtCore.QRect(80, 140, 381, 41))
        self.textcity.setStyleSheet("background:none;\n"
"font: 10pt \"Tahoma\";\n"
"color:white;")
        self.textcity.setObjectName("textcity")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(150, 30, 261, 91))
        self.title.setStyleSheet("background:none;\n"
"font: 28pt \"Tahoma\";\n"
"color:white;")
        self.title.setObjectName("title")
        self.Selection = QtWidgets.QComboBox(self.centralwidget)
        self.Selection.setGeometry(QtCore.QRect(180, 190, 181, 22))
        self.Selection.setStyleSheet("background:none;\n"
"font:  \"Tahoma\";\n"
"color:black;")
        self.Selection.setObjectName("Selection")
        self.Selection.addItem("")
        self.Selection.addItem("")
        self.Selection.addItem("")
        self.Selection.addItem("")
        self.Selection.addItem("")
        self.backbutton = QtWidgets.QPushButton(self.centralwidget)
        self.backbutton.setGeometry(QtCore.QRect(20, 30, 75, 23))
        self.backbutton.setStyleSheet("background:none;\n"
"font:  \"Tahoma\";\n"
"color:black;")
        self.backbutton.setObjectName("backbutton")
        select_win.setCentralWidget(self.centralwidget)

        self.retranslateUi(select_win)
        QtCore.QMetaObject.connectSlotsByName(select_win)

    def retranslateUi(self, select_win):
        _translate = QtCore.QCoreApplication.translate
        select_win.setWindowTitle(_translate("select_win", "MainWindow"))
        self.next.setText(_translate("select_win", "NEXT"))
        self.textcity.setText(_translate("select_win", "Please Select whoose load you want to Calculate"))
        self.title.setText(_translate("select_win", "HVAC CEP"))
        self.Selection.setItemText(0, _translate("select_win", "Door"))
        self.Selection.setItemText(1, _translate("select_win", "Appliances"))
        self.Selection.setItemText(2, _translate("select_win", "Walls"))
        self.Selection.setItemText(3, _translate("select_win", "Window"))
        self.Selection.setItemText(4, _translate("select_win", "Roof"))
        self.backbutton.setText(_translate("select_win", "back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    select_win = QtWidgets.QMainWindow()
    ui = Ui_select_win()
    ui.setupUi(select_win)
    select_win.show()
    sys.exit(app.exec_())
