# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windows_a.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(655, 387)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 340, 161, 16))
        self.label_2.setObjectName("label_2")
        self.textortation_2 = QtWidgets.QLabel(self.centralwidget)
        self.textortation_2.setGeometry(QtCore.QRect(380, 130, 111, 20))
        self.textortation_2.setStyleSheet("font: 75 8pt \"Arial\";\n"
"font: 87 9pt \"Arial Black\";")
        self.textortation_2.setObjectName("textortation_2")
        self.cl = QtWidgets.QLabel(self.centralwidget)
        self.cl.setGeometry(QtCore.QRect(230, 340, 55, 16))
        self.cl.setObjectName("cl")
        self.door_text = QtWidgets.QLabel(self.centralwidget)
        self.door_text.setGeometry(QtCore.QRect(250, 130, 41, 20))
        self.door_text.setStyleSheet("font: 75 8pt \"Arial\";\n"
"font: 87 9pt \"Arial Black\";")
        self.door_text.setText("")
        self.door_text.setObjectName("door_text")
        self.doordropdown = QtWidgets.QComboBox(self.centralwidget)
        self.doordropdown.setGeometry(QtCore.QRect(50, 160, 131, 22))
        self.doordropdown.setObjectName("doordropdown")
        self.doordropdown.addItem("")
        self.doordropdown.addItem("")
        self.wd_temp_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.wd_temp_1.setGeometry(QtCore.QRect(170, 260, 91, 20))
        self.wd_temp_1.setObjectName("wd_temp_1")
        self.ortationdrop_1 = QtWidgets.QComboBox(self.centralwidget)
        self.ortationdrop_1.setGeometry(QtCore.QRect(230, 160, 71, 22))
        self.ortationdrop_1.setObjectName("ortationdrop_1")
        self.ortationdrop_1.addItem("")
        self.ortationdrop_1.addItem("")
        self.ortationdrop_1.addItem("")
        self.ortationdrop_1.addItem("")
        self.backbutton = QtWidgets.QPushButton(self.centralwidget)
        self.backbutton.setGeometry(QtCore.QRect(20, 20, 91, 23))
        self.backbutton.setObjectName("backbutton")
        self.lng_temp_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lng_temp_1.setGeometry(QtCore.QRect(170, 210, 91, 20))
        self.lng_temp_1.setObjectName("lng_temp_1")
        self.floor = QtWidgets.QComboBox(self.centralwidget)
        self.floor.setGeometry(QtCore.QRect(390, 160, 81, 22))
        self.floor.setObjectName("floor")
        self.floor.addItem("")
        self.floor.addItem("")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(220, 20, 191, 71))
        self.title.setStyleSheet("font: 28pt \"Tahoma\";")
        self.title.setObjectName("title")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 310, 161, 16))
        self.label.setObjectName("label")
        self.nextpushButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextpushButton.setGeometry(QtCore.QRect(550, 330, 91, 23))
        self.nextpushButton.setObjectName("nextpushButton")
        self.rl = QtWidgets.QLabel(self.centralwidget)
        self.rl.setGeometry(QtCore.QRect(230, 310, 55, 16))
        self.rl.setObjectName("rl")
        self.doortypetext = QtWidgets.QLabel(self.centralwidget)
        self.doortypetext.setGeometry(QtCore.QRect(55, 130, 121, 20))
        self.doortypetext.setStyleSheet("font: 75 8pt \"Arial\";\n"
"font: 87 9pt \"Arial Black\";")
        self.doortypetext.setObjectName("doortypetext")
        self.textortation = QtWidgets.QLabel(self.centralwidget)
        self.textortation.setGeometry(QtCore.QRect(230, 130, 111, 20))
        self.textortation.setStyleSheet("font: 75 8pt \"Arial\";\n"
"font: 87 9pt \"Arial Black\";")
        self.textortation.setObjectName("textortation")
        self.lenghttext = QtWidgets.QLabel(self.centralwidget)
        self.lenghttext.setGeometry(QtCore.QRect(70, 210, 111, 20))
        self.lenghttext.setStyleSheet("font: 75 8pt \"Arial\";\n"
"font: 87 9pt \"Arial Black\";")
        self.lenghttext.setObjectName("lenghttext")
        self.widthtext = QtWidgets.QLabel(self.centralwidget)
        self.widthtext.setGeometry(QtCore.QRect(70, 260, 81, 20))
        self.widthtext.setStyleSheet("font: 75 8pt \"Arial\";\n"
"font: 87 9pt \"Arial Black\";")
        self.widthtext.setObjectName("widthtext")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "The total Conduction load is "))
        self.textortation_2.setText(_translate("MainWindow", "Floor"))
        self.cl.setText(_translate("MainWindow", "TextLabel"))
        self.doordropdown.setItemText(0, _translate("MainWindow", "Single Pane"))
        self.doordropdown.setItemText(1, _translate("MainWindow", "Double Pane"))
        self.ortationdrop_1.setItemText(0, _translate("MainWindow", "North"))
        self.ortationdrop_1.setItemText(1, _translate("MainWindow", "South"))
        self.ortationdrop_1.setItemText(2, _translate("MainWindow", "East"))
        self.ortationdrop_1.setItemText(3, _translate("MainWindow", "West"))
        self.backbutton.setText(_translate("MainWindow", "BACK"))
        self.floor.setItemText(0, _translate("MainWindow", "Ground"))
        self.floor.setItemText(1, _translate("MainWindow", "First"))
        self.title.setText(_translate("MainWindow", "WEC CLTD"))
        self.label.setText(_translate("MainWindow", "The total Radiation load is "))
        self.nextpushButton.setText(_translate("MainWindow", "NEXT"))
        self.rl.setText(_translate("MainWindow", ""))
        self.doortypetext.setText(_translate("MainWindow", "Windows Type"))
        self.textortation.setText(_translate("MainWindow", "Oritation"))
        self.lenghttext.setText(_translate("MainWindow", "Length(ft)"))
        self.widthtext.setText(_translate("MainWindow", "Width (ft)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
