# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_app(object):
    def setupUi(self, app):
        app.setObjectName("app")
        app.resize(742, 500)
        app.setMinimumSize(QtCore.QSize(742, 500))
        app.setMaximumSize(QtCore.QSize(742, 500))
        app.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(41, 48, 54, 255), stop:1 rgba(101, 91, 76, 255));")
        self.centralwidget = QtWidgets.QWidget(app)
        self.centralwidget.setObjectName("centralwidget")
        self.cal_1 = QtWidgets.QPushButton(self.centralwidget)
        self.cal_1.setGeometry(QtCore.QRect(60, 220, 91, 23))
        self.cal_1.setStyleSheet("background:none;\n"
"font:  \"Tahoma\";\n"
"color:black;")
        self.cal_1.setObjectName("cal_1")
        self.doortypetext = QtWidgets.QLabel(self.centralwidget)
        self.doortypetext.setGeometry(QtCore.QRect(70, 80, 131, 31))
        self.doortypetext.setStyleSheet("background:none;\n"
"font: 10pt \"Tahoma\";\n"
"color:white;")
        self.doortypetext.setObjectName("doortypetext")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(240, 10, 241, 71))
        self.title.setStyleSheet("font: 28pt \"Helvetica\";\n"
"background:none;\n"
"color:white;")
        self.title.setObjectName("title")
        self.backbutton = QtWidgets.QPushButton(self.centralwidget)
        self.backbutton.setGeometry(QtCore.QRect(20, 30, 91, 23))
        self.backbutton.setStyleSheet("background:none;\n"
"font:  \"Tahoma\";\n"
"color:black;")
        self.backbutton.setObjectName("backbutton")
        self.people = QtWidgets.QLineEdit(self.centralwidget)
        self.people.setGeometry(QtCore.QRect(180, 120, 101, 20))
        self.people.setStyleSheet("background:none;\n"
"font:  \"Tahoma\";\n"
"color:black;")
        self.people.setObjectName("people")
        self.rl = QtWidgets.QLabel(self.centralwidget)
        self.rl.setGeometry(QtCore.QRect(130, 150, 55, 16))
        self.rl.setStyleSheet("background:none;\n"
"font: 8pt \"Tahoma\";\n"
"color:white;")
        self.rl.setObjectName("rl")
        self.watt = QtWidgets.QLineEdit(self.centralwidget)
        self.watt.setGeometry(QtCore.QRect(520, 119, 101, 21))
        self.watt.setStyleSheet("background:none;\n"
"font:  \"Tahoma\";\n"
"color:black;")
        self.watt.setObjectName("watt")
        self.doortypetext_2 = QtWidgets.QLabel(self.centralwidget)
        self.doortypetext_2.setGeometry(QtCore.QRect(20, 110, 151, 31))
        self.doortypetext_2.setStyleSheet("background:none;\n"
"font: 10pt \"Tahoma\";\n"
"color:white;")
        self.doortypetext_2.setObjectName("doortypetext_2")
        self.doortypetext_3 = QtWidgets.QLabel(self.centralwidget)
        self.doortypetext_3.setGeometry(QtCore.QRect(380, 110, 151, 31))
        self.doortypetext_3.setStyleSheet("background:none;\n"
"font: 10pt \"Tahoma\";\n"
"color:white;")
        self.doortypetext_3.setObjectName("doortypetext_3")
        self.doortypetext_4 = QtWidgets.QLabel(self.centralwidget)
        self.doortypetext_4.setGeometry(QtCore.QRect(20, 140, 131, 31))
        self.doortypetext_4.setStyleSheet("background:none;\n"
"font: 10pt \"Tahoma\";\n"
"color:white;")
        self.doortypetext_4.setObjectName("doortypetext_4")
        self.rl_2 = QtWidgets.QLabel(self.centralwidget)
        self.rl_2.setGeometry(QtCore.QRect(130, 180, 55, 16))
        self.rl_2.setStyleSheet("background:none;\n"
"font: 8pt \"Tahoma\";\n"
"color:white;")
        self.rl_2.setObjectName("rl_2")
        self.doortypetext_5 = QtWidgets.QLabel(self.centralwidget)
        self.doortypetext_5.setGeometry(QtCore.QRect(20, 170, 131, 31))
        self.doortypetext_5.setStyleSheet("background:none;\n"
"font: 10pt \"Tahoma\";\n"
"color:white;")
        self.doortypetext_5.setObjectName("doortypetext_5")
        self.doortypetext_6 = QtWidgets.QLabel(self.centralwidget)
        self.doortypetext_6.setGeometry(QtCore.QRect(380, 150, 131, 31))
        self.doortypetext_6.setStyleSheet("background:none;\n"
"font: 10pt \"Tahoma\";\n"
"color:white;")
        self.doortypetext_6.setObjectName("doortypetext_6")
        self.rl_3 = QtWidgets.QLabel(self.centralwidget)
        self.rl_3.setGeometry(QtCore.QRect(490, 160, 55, 16))
        self.rl_3.setStyleSheet("background:none;\n"
"font: 8pt \"Tahoma\";\n"
"color:white;")
        self.rl_3.setObjectName("rl_3")
        self.cal_2 = QtWidgets.QPushButton(self.centralwidget)
        self.cal_2.setGeometry(QtCore.QRect(500, 220, 91, 23))
        self.cal_2.setStyleSheet("background:none;\n"
"font:  \"Tahoma\";\n"
"color:black;")
        self.cal_2.setObjectName("cal_2")
        self.cal_3 = QtWidgets.QPushButton(self.centralwidget)
        self.cal_3.setGeometry(QtCore.QRect(70, 420, 91, 23))
        self.cal_3.setStyleSheet("background:none;\n"
"font:  \"Tahoma\";\n"
"color:black;")
        self.cal_3.setObjectName("cal_3")
        self.doortypetext_7 = QtWidgets.QLabel(self.centralwidget)
        self.doortypetext_7.setGeometry(QtCore.QRect(30, 370, 131, 31))
        self.doortypetext_7.setStyleSheet("background:none;\n"
"font: 10pt \"Tahoma\";\n"
"color:white;")
        self.doortypetext_7.setObjectName("doortypetext_7")
        self.doortypetext_8 = QtWidgets.QLabel(self.centralwidget)
        self.doortypetext_8.setGeometry(QtCore.QRect(70, 290, 131, 31))
        self.doortypetext_8.setStyleSheet("background:none;\n"
"font: 10pt \"Tahoma\";\n"
"color:white;")
        self.doortypetext_8.setObjectName("doortypetext_8")
        self.rl_4 = QtWidgets.QLabel(self.centralwidget)
        self.rl_4.setGeometry(QtCore.QRect(140, 380, 55, 16))
        self.rl_4.setStyleSheet("background:none;\n"
"font: 8pt \"Tahoma\";\n"
"color:white;")
        self.rl_4.setObjectName("rl_4")
        self.rl_5 = QtWidgets.QLabel(self.centralwidget)
        self.rl_5.setGeometry(QtCore.QRect(140, 350, 55, 16))
        self.rl_5.setStyleSheet("background:none;\n"
"font: 8pt \"Tahoma\";\n"
"color:white;")
        self.rl_5.setObjectName("rl_5")
        self.doortypetext_9 = QtWidgets.QLabel(self.centralwidget)
        self.doortypetext_9.setGeometry(QtCore.QRect(30, 340, 131, 31))
        self.doortypetext_9.setStyleSheet("background:none;\n"
"font: 10pt \"Tahoma\";\n"
"color:white;")
        self.doortypetext_9.setObjectName("doortypetext_9")
        self.rl_6 = QtWidgets.QLabel(self.centralwidget)
        self.rl_6.setGeometry(QtCore.QRect(380, 380, 55, 16))
        self.rl_6.setStyleSheet("background:none;\n"
"font: 8pt \"Tahoma\";\n"
"color:white;")
        self.rl_6.setObjectName("rl_6")
        self.rl_7 = QtWidgets.QLabel(self.centralwidget)
        self.rl_7.setGeometry(QtCore.QRect(380, 350, 55, 16))
        self.rl_7.setStyleSheet("background:none;\n"
"font: 8pt \"Tahoma\";\n"
"color:white;")
        self.rl_7.setObjectName("rl_7")
        self.doortypetext_10 = QtWidgets.QLabel(self.centralwidget)
        self.doortypetext_10.setGeometry(QtCore.QRect(310, 290, 131, 31))
        self.doortypetext_10.setStyleSheet("background:none;\n"
"font: 10pt \"Tahoma\";\n"
"color:white;")
        self.doortypetext_10.setObjectName("doortypetext_10")
        self.cal_4 = QtWidgets.QPushButton(self.centralwidget)
        self.cal_4.setGeometry(QtCore.QRect(310, 420, 91, 23))
        self.cal_4.setStyleSheet("background:none;\n"
"font:  \"Tahoma\";\n"
"color:black;")
        self.cal_4.setObjectName("cal_4")
        self.doortypetext_11 = QtWidgets.QLabel(self.centralwidget)
        self.doortypetext_11.setGeometry(QtCore.QRect(270, 340, 131, 31))
        self.doortypetext_11.setStyleSheet("background:none;\n"
"font: 10pt \"Tahoma\";\n"
"color:white;")
        self.doortypetext_11.setObjectName("doortypetext_11")
        self.doortypetext_12 = QtWidgets.QLabel(self.centralwidget)
        self.doortypetext_12.setGeometry(QtCore.QRect(270, 370, 131, 31))
        self.doortypetext_12.setStyleSheet("background:none;\n"
"font: 10pt \"Tahoma\";\n"
"color:white;")
        self.doortypetext_12.setObjectName("doortypetext_12")
        self.rl_8 = QtWidgets.QLabel(self.centralwidget)
        self.rl_8.setGeometry(QtCore.QRect(600, 380, 55, 16))
        self.rl_8.setStyleSheet("background:none;\n"
"font: 8pt \"Tahoma\";\n"
"color:white;")
        self.rl_8.setObjectName("rl_8")
        self.cal_5 = QtWidgets.QPushButton(self.centralwidget)
        self.cal_5.setGeometry(QtCore.QRect(530, 420, 91, 23))
        self.cal_5.setStyleSheet("background:none;\n"
"font:  \"Tahoma\";\n"
"color:black;")
        self.cal_5.setObjectName("cal_5")
        self.doortypetext_13 = QtWidgets.QLabel(self.centralwidget)
        self.doortypetext_13.setGeometry(QtCore.QRect(490, 340, 131, 31))
        self.doortypetext_13.setStyleSheet("background:none;\n"
"font: 10pt \"Tahoma\";\n"
"color:white;")
        self.doortypetext_13.setObjectName("doortypetext_13")
        self.doortypetext_14 = QtWidgets.QLabel(self.centralwidget)
        self.doortypetext_14.setGeometry(QtCore.QRect(490, 370, 131, 31))
        self.doortypetext_14.setStyleSheet("background:none;\n"
"font: 10pt \"Tahoma\";\n"
"color:white;")
        self.doortypetext_14.setObjectName("doortypetext_14")
        self.rl_9 = QtWidgets.QLabel(self.centralwidget)
        self.rl_9.setGeometry(QtCore.QRect(600, 350, 55, 16))
        self.rl_9.setStyleSheet("background:none;\n"
"font: 8pt \"Tahoma\";\n"
"color:white;")
        self.rl_9.setObjectName("rl_9")
        self.doortypetext_15 = QtWidgets.QLabel(self.centralwidget)
        self.doortypetext_15.setGeometry(QtCore.QRect(530, 290, 131, 31))
        self.doortypetext_15.setStyleSheet("background:none;\n"
"font: 10pt \"Tahoma\";\n"
"color:white;")
        self.doortypetext_15.setObjectName("doortypetext_15")
        self.doortypetext_16 = QtWidgets.QLabel(self.centralwidget)
        self.doortypetext_16.setGeometry(QtCore.QRect(470, 80, 131, 31))
        self.doortypetext_16.setStyleSheet("background:none;\n"
"font: 10pt \"Tahoma\";\n"
"color:white;")
        self.doortypetext_16.setObjectName("doortypetext_16")
        self.incdata = QtWidgets.QLabel(self.centralwidget)
        self.incdata.setGeometry(QtCore.QRect(280, 80, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.incdata.setFont(font)
        self.incdata.setStyleSheet("color:white;background-color:transparent;")
        self.incdata.setObjectName("incdata")
        app.setCentralWidget(self.centralwidget)

        self.retranslateUi(app)
        QtCore.QMetaObject.connectSlotsByName(app)

    def retranslateUi(self, app):
        _translate = QtCore.QCoreApplication.translate
        app.setWindowTitle(_translate("app", "MainWindow"))
        self.cal_1.setText(_translate("app", "Calculate"))
        self.doortypetext.setText(_translate("app", "Solar Loads"))
        self.title.setText(_translate("app", "WEC CLTD"))
        self.backbutton.setText(_translate("app", "BACK"))
        self.rl.setText(_translate("app", "TextLabel"))
        self.doortypetext_2.setText(_translate("app", "Enter no of peoples"))
        self.doortypetext_3.setText(_translate("app", "Enter Watts No."))
        self.doortypetext_4.setText(_translate("app", "Qsensible"))
        self.rl_2.setText(_translate("app", "Qlatent"))
        self.doortypetext_5.setText(_translate("app", "Qlatent"))
        self.doortypetext_6.setText(_translate("app", "Q :"))
        self.rl_3.setText(_translate("app", "text"))
        self.cal_2.setText(_translate("app", "Calculate"))
        self.cal_3.setText(_translate("app", "Calculate"))
        self.doortypetext_7.setText(_translate("app", "Qlatent"))
        self.doortypetext_8.setText(_translate("app", "Fridges"))
        self.rl_4.setText(_translate("app", "Fridges"))
        self.rl_5.setText(_translate("app", "Fridges"))
        self.doortypetext_9.setText(_translate("app", "Qsensible"))
        self.rl_6.setText(_translate("app", "Fridges"))
        self.rl_7.setText(_translate("app", "Fridges"))
        self.doortypetext_10.setText(_translate("app", "Fridges"))
        self.cal_4.setText(_translate("app", "Calculate"))
        self.doortypetext_11.setText(_translate("app", "Qsensible"))
        self.doortypetext_12.setText(_translate("app", "Qlatent"))
        self.rl_8.setText(_translate("app", "0"))
        self.cal_5.setText(_translate("app", "Calculate"))
        self.doortypetext_13.setText(_translate("app", "Qsensible"))
        self.doortypetext_14.setText(_translate("app", "Qlatent"))
        self.rl_9.setText(_translate("app", "Fridges"))
        self.doortypetext_15.setText(_translate("app", "Microwave Oven"))
        self.doortypetext_16.setText(_translate("app", "Light"))
        self.incdata.setText(_translate("app", ""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app = QtWidgets.QMainWindow()
    ui = Ui_app()
    ui.setupUi(app)
    app.show()
    sys.exit(app.exec_())
