# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Roof.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Roof(object):
    def setupUi(self, Roof):
        Roof.setObjectName("Roof")
        Roof.resize(760, 489)
        Roof.setMinimumSize(QtCore.QSize(760, 489))
        Roof.setMaximumSize(QtCore.QSize(760, 489))
        Roof.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(41, 48, 54, 255), stop:1 rgba(101, 91, 76, 255));")
        self.centralwidget = QtWidgets.QWidget(Roof)
        self.centralwidget.setObjectName("centralwidget")
        self.textortation_2 = QtWidgets.QLabel(self.centralwidget)
        self.textortation_2.setGeometry(QtCore.QRect(430, 160, 61, 20))
        self.textortation_2.setStyleSheet("background:none;\n"
"font: 12pt \"Tahoma\";\n"
"color:white;")
        self.textortation_2.setObjectName("textortation_2")
        self.door_text = QtWidgets.QLabel(self.centralwidget)
        self.door_text.setGeometry(QtCore.QRect(280, 160, 91, 20))
        self.door_text.setStyleSheet("background:none;\n"
"font: 12pt \"Tahoma\";\n"
"color:white;")
        self.door_text.setObjectName("door_text")
        self.wd_temp_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.wd_temp_1.setGeometry(QtCore.QRect(280, 300, 131, 20))
        self.wd_temp_1.setStyleSheet("background:none;\n"
"font:  \"Tahoma\";\n"
"color:black;")
        self.wd_temp_1.setObjectName("wd_temp_1")
        self.backbutton = QtWidgets.QPushButton(self.centralwidget)
        self.backbutton.setGeometry(QtCore.QRect(30, 30, 91, 23))
        self.backbutton.setStyleSheet("background:none;\n"
"font: \"Tahoma\";\n"
"color:black;")
        self.backbutton.setObjectName("backbutton")
        self.lng_temp_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lng_temp_1.setGeometry(QtCore.QRect(280, 260, 131, 20))
        self.lng_temp_1.setStyleSheet("background:none;\n"
"font:  \"Tahoma\";\n"
"color:black;")
        self.lng_temp_1.setObjectName("lng_temp_1")
        self.floor = QtWidgets.QComboBox(self.centralwidget)
        self.floor.setGeometry(QtCore.QRect(430, 190, 81, 22))
        self.floor.setStyleSheet("background:none;\n"
"font:  \"Tahoma\";\n"
"color:black;")
        self.floor.setObjectName("floor")
        self.floor.addItem("")
        self.floor.addItem("")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(250, 50, 241, 71))
        self.title.setStyleSheet("background:none;\n"
"font: 28pt \"Tahoma\";\n"
"color:white;")
        self.title.setObjectName("title")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 360, 161, 16))
        self.label.setStyleSheet("background:none;\n"
"font: 8pt \"Tahoma\";\n"
"color:white;")
        self.label.setObjectName("label")
        self.next3 = QtWidgets.QPushButton(self.centralwidget)
        self.next3.setGeometry(QtCore.QRect(570, 400, 101, 23))
        self.next3.setStyleSheet("background:none;\n"
"font: 8pt \"Tahoma\";\n"
"color:black;")
        self.next3.setObjectName("next3")
        self.rl = QtWidgets.QLabel(self.centralwidget)
        self.rl.setGeometry(QtCore.QRect(360, 360, 101, 16))
        self.rl.setStyleSheet("background:none;\n"
"font: 8pt \"Tahoma\";\n"
"color:white;")
        self.rl.setObjectName("rl")
        self.doordropdown_2 = QtWidgets.QComboBox(self.centralwidget)
        self.doordropdown_2.setGeometry(QtCore.QRect(280, 190, 131, 22))
        self.doordropdown_2.setStyleSheet("background:none;\n"
"font:  \"Tahoma\";\n"
"color:black;")
        self.doordropdown_2.setObjectName("doordropdown_2")
        self.doordropdown_2.addItem("")
        self.doordropdown_2.addItem("")
        self.doordropdown_2.addItem("")
        self.doordropdown_2.addItem("")
        self.lenghttext = QtWidgets.QLabel(self.centralwidget)
        self.lenghttext.setGeometry(QtCore.QRect(170, 253, 111, 31))
        self.lenghttext.setStyleSheet("background:none;\n"
"font: 12pt \"Tahoma\";\n"
"color:white;")
        self.lenghttext.setObjectName("lenghttext")
        self.widthtext = QtWidgets.QLabel(self.centralwidget)
        self.widthtext.setGeometry(QtCore.QRect(175, 298, 81, 21))
        self.widthtext.setStyleSheet("background:none;\n"
"font: 12pt \"Tahoma\";\n"
"color:white;")
        self.widthtext.setObjectName("widthtext")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(530, 240, 111, 31))
        self.label_2.setStyleSheet("background:none;\n"
"font: 8pt \"Tahoma\";\n"
"color:white;")
        self.label_2.setObjectName("label_2")
        Roof.setCentralWidget(self.centralwidget)

        self.retranslateUi(Roof)
        QtCore.QMetaObject.connectSlotsByName(Roof)

    def retranslateUi(self, Roof):
        _translate = QtCore.QCoreApplication.translate
        Roof.setWindowTitle(_translate("Roof", "MainWindow"))
        self.textortation_2.setText(_translate("Roof", "Floor"))
        self.door_text.setText(_translate("Roof", "Roof"))
        self.backbutton.setText(_translate("Roof", "BACK"))
        self.floor.setItemText(0, _translate("Roof", "Ground"))
        self.floor.setItemText(1, _translate("Roof", "First"))
        self.title.setText(_translate("Roof", "WEC CLTD"))
        self.label.setText(_translate("Roof", "The total Radiation load is "))
        self.next3.setText(_translate("Roof", "NEXT"))
        self.rl.setText(_translate("Roof", ""))
        self.doordropdown_2.setItemText(0, _translate("Roof", "1"))
        self.doordropdown_2.setItemText(1, _translate("Roof", "2"))
        self.doordropdown_2.setItemText(2, _translate("Roof", "3"))
        self.doordropdown_2.setItemText(3, _translate("Roof", "4"))
        self.lenghttext.setText(_translate("Roof", "Length(ft)"))
        self.widthtext.setText(_translate("Roof", "Width (ft)"))
        self.label_2.setText(_translate("Roof", ""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Roof = QtWidgets.QMainWindow()
    ui = Ui_Roof()
    ui.setupUi(Roof)
    Roof.show()
    sys.exit(app.exec_())
